defmodule LSWeb.Router do
  use LSWeb, :router

  import LSWeb.UserAuth

  pipeline :public do
    plug :accepts, ["html"]
    plug :put_root_layout, html: {LSWeb.Layouts, :public_root}
    plug :put_secure_browser_headers
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {LSWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_scope_for_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Stripe webhook — BEFORE browser pipeline (no CSRF)
  scope "/webhooks", LSWeb do
    pipe_through :api
    post "/stripe", StripeWebhookController, :handle_webhook
  end

  # Public marketing (existing — keep as-is)
  scope "/", LSWeb do
    pipe_through :public

    # Redirect /signup to /users/register (all marketing CTAs point here)
    get "/signup", RedirectController, :signup
    get "/login", RedirectController, :login

    get "/", PageController, :home
    get "/search", SearchController, :search
    get "/pricing", PageController, :pricing
    get "/features", PageController, :features

    get "/store/:slug", StoreController, :show
    get "/shopify/:slug", StoreController, :show_shopify
    get "/website/:slug", StoreController, :show_website
    get "/tech/:slug", TechController, :show
    get "/compare/:slug", CompareController, :show
    get "/top/:slug", TopController, :show

    get "/apps", DirectoryController, :apps
    get "/countries", DirectoryController, :countries

    get "/alternatives/:competitor", AlternativesController, :show

    get "/tools/shopify-checker", ToolsController, :shopify_checker
    get "/tools/tech-lookup", ToolsController, :tech_lookup
    get "/api/tools/lookup", ToolsController, :api_lookup
    get "/api/tech/suggest", ToolsController, :api_tech_suggest

    get "/new-stores", FeedController, :new_stores

    get "/privacy", LegalController, :privacy
    get "/terms", LegalController, :terms

    get "/sitemap.xml", SitemapController, :index
  end

  # Admin dashboard (internal)
  scope "/admin", LSWeb do
    pipe_through :browser
    live "/", DashboardLive, :index
  end

  # Auth pages (generated by phx.gen.auth)
  scope "/", LSWeb do
    pipe_through [:browser]

    live_session :current_user,
      on_mount: [{LSWeb.UserAuth, :mount_current_scope}] do
      live "/users/register", UserLive.Registration, :new
      live "/users/log-in", UserLive.Login, :new
      live "/users/log-in/:token", UserLive.Confirmation, :new
    end

    post "/users/log-in", UserSessionController, :create
    delete "/users/log-out", UserSessionController, :delete
  end

  # Authenticated app routes
  scope "/", LSWeb do
    pipe_through [:browser, :require_authenticated_user]

    live_session :require_authenticated_user,
      on_mount: [{LSWeb.UserAuth, :require_authenticated}] do
      live "/dashboard", ExplorerLive, :index
      live "/users/settings", UserLive.Settings, :edit
      live "/users/settings/confirm-email/:token", UserLive.Settings, :confirm_email
    end

    post "/users/update-password", UserSessionController, :update_password
    post "/subscription/checkout/:plan/:period", SubscriptionController, :create_checkout_session
    post "/subscription/portal", SubscriptionController, :create_billing_portal_session
    get "/dashboard/export", ExportController, :csv
  end

  # Dev routes
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser
      live_dashboard "/phoenix", metrics: LSWeb.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end
