defmodule LS.Schema.Migration do
  @moduledoc """
  The v1 to v2 data model migration, as SQL (2026-10-01).

  `statements/0` is the ordered list of statements the runbook
  (`clickhouse/migrations/025_data_model_v2.sh`) applies with the fleet
  stopped. It is generated from the same modules the running code uses
  (`LS.Schema.Columns`, `LS.Schema.Changes`, `LS.Tech.Catalog`), so the
  table the compactor writes into is by construction the table this
  creates. `mix ls.schema_v2` writes it to
  `clickhouse/migrations/025_data_model_v2.sql`, the committed record.

  Order, and why:

    1. new tables first (`tech_catalog`, `http_pages`, `changes_log`,
       `businesses_v2`): additive, nothing running depends on them;
    2. the catalog rows, which the v1 transform needs;
    3. the six new log columns on `enrich_log` (ALTER ADD COLUMN, 0.056 s
       measured on prod);
    4. the one-time transform of `businesses` into `businesses_v2`
       (22.8M rows, one INSERT SELECT, memory-bounded by max_threads);
    5. the `biz_signal` import into `changes_log`;
    6. legacy ALIAS columns on `businesses_v2`, one release of
       compatibility for readers not yet on the new names;
    7. the table renames, done by the runbook: one RENAME per table that
       exists, then `businesses TO bak_businesses_v1, businesses_v2 TO
       businesses` in one atomic statement.

  Materialized views and plain views that reference renamed tables are
  recreated by the runbook from `SHOW CREATE TABLE` with the names
  substituted, not from text kept here, so they cannot drift from what the
  server holds. Drops (the v1 `businesses` kept as `bak_businesses_v1`,
  `biz_signal`, the snippet columns, `bak_nxfix_20260730`) are a separate
  step the owner runs after validation.
  """

  alias LS.Schema.{Changes, Columns, Tables}
  alias LS.Tech.Catalog

  @new_log_columns [
    {"http_phone", "String DEFAULT ''"},
    {"http_address", "String DEFAULT ''"},
    {"http_social_links", "String DEFAULT ''"},
    {"http_company_id", "String DEFAULT ''"},
    {"http_nav_links", "String DEFAULT ''"},
    {"http_shopify_app_handles", "String DEFAULT ''"}
  ]

  @doc "Ordered `{label, sql}` pairs. Table renames are last; views are the runbook's job."
  def statements do
    v2 = "businesses_v2"

    creates = [
      {"create tech_catalog", Changes.catalog_ddl()},
      {"create http_pages", Changes.pages_ddl()},
      {"create changes_log", Changes.ddl()},
      {"create businesses_v2", Columns.ddl(v2)}
    ]

    catalog = [{"fill tech_catalog", catalog_insert_sql()}]

    log_cols =
      for {name, type} <- @new_log_columns do
        {"add #{name} to domains_history", "ALTER TABLE domains_history ADD COLUMN IF NOT EXISTS `#{name}` #{type}"}
      end

    transform = [{"transform businesses into businesses_v2", v1_transform_sql(v2)}]
    signals = [{"import biz_signal into changes_log", Changes.import_v1_sql()}]
    aliases = for sql <- Columns.legacy_alias_ddl(v2), do: {"legacy alias", sql}

    # Table renames are the runbook's job: it renames only tables that exist
    # (RENAME TABLE has no IF EXISTS), then swaps the product table atomically.
    creates ++ catalog ++ log_cols ++ transform ++ signals ++ aliases
  end

  @doc "The statements as one SQL script (clickhouse-client --multiquery)."
  def script do
    header = "-- Generated by `mix ls.schema_v2` from LS.Schema.* on #{Date.utc_today()}. Do not edit by hand.\n\n"

    body =
      Enum.map_join(statements(), "\n\n", fn {label, sql} -> "-- #{label}\n#{String.trim_trailing(sql)};" end)

    header <> body <> "\n"
  end

  @doc "INSERT of the catalog rows (ReplacingMergeTree: re-running refreshes, never duplicates after merge)."
  def catalog_insert_sql do
    rows = Enum.map_join(Catalog.table_rows(), ", ", fn {n, c, e} -> "('#{esc(n)}', '#{c}', '#{e}')" end)
    "INSERT INTO #{Tables.tech_catalog()} (name, category, ecosystem) VALUES #{rows}"
  end

  @doc """
  The one-time INSERT SELECT from the v1 table (`b`) into the v2 table.

  No ORDER BY / LIMIT 1 BY: deduplicating 22.8M wide rows would sort the
  whole 9.3 GB table in memory, past the 3 GB this query is allowed on the
  shared master. The hourly optimizer keeps v1 duplicates at 0.07%; they
  carry over as versions with the same compiled_at and the ReplacingMergeTree
  collapses them at the next merge. Streaming, two threads, no spill.
  """
  def v1_transform_sql(target \\ "businesses_v2", source \\ "businesses") do
    cols = Enum.join(Columns.insert_columns(), ", ")

    """
    INSERT INTO #{target} (#{cols})
    WITH #{LS.Clickhouse.Compact.catalog_with()}
    SELECT
      #{Columns.v1_select()}
    FROM #{source} AS b
    SETTINGS max_threads = 2, max_insert_threads = 2, max_memory_usage = 3000000000
    """
  end

  @doc "One atomic RENAME TABLE covering every rename, the product table last."
  def rename_sql do
    pairs =
      Enum.map(Tables.renames(), fn {old, new} -> "#{old} TO #{new}" end) ++
        ["businesses TO bak_businesses_v1", "businesses_v2 TO businesses"]

    "RENAME TABLE " <> Enum.join(pairs, ", ")
  end

  @doc """
  Names of the materialized views and views the runbook recreates after the
  rename, with the text substitutions it applies to their SHOW CREATE.
  """
  def view_renames do
    Enum.map(Tables.renames(), fn {old, new} -> {"ls.#{old}", "ls.#{new}"} end) ++
      [{"mv_domains_current", "mv_domains"}]
  end

  defp esc(s), do: String.replace(s, "'", "\\'")
end
